#!/bin/bash
checkfile () {
echo $#
echo $1
if [ $# -gt 0 ]; then
if [[ -f $1 && -r $1 ]]
then
echo "$1 is a readable file"
else
echo "$1 is not a readable file"
fi
fi
}

checkfile .
checkfile counter
checkfile 123

