#!/bin/bash
xaliq () {
read -p "Name of the file:" file #idk the exact difference between ex2 and ex3
if [[ -r $file && -w $file && -x $file ]]; then
echo "it is accessible"				#but i used function here
else
echo "it is not accessible"
fi
}
xaliq

