#!/bin/bash
echo "enter any positive number"
read a
while [ $a -ne 0 ]
do
	let digit=$(($a%10))
	let remainder=$(($digit%2))	
        if [ $remainder -eq 0 ]; then
	echo "$digit"
	fi
	let a=$(($a/10))
done
