#!/bin/bash
echo "enter any number"
read a
i=0
while [ $a -ne 0 ]
do
	let digit=$((a%10))
	if [ $digit -gt $i ]; then
	i=$digit
	else
	i=$i
	fi	
	let a=$((a/10))
done
echo "the biggest number is $i"
	
