#!/bin/bash
echo "enter any number"
read a
result=1
i=2
if [ $a -eq 0 ]; then
	echo "0!=1"
elif [ $a -lt 0 ]; then
	echo "invalid"
else
	while [ $i -le $a ]
	do
	  let result=$result*$i
	  let i=$i+1  
	done
	echo "$a!=$result"
fi
