#!/bin/bash
local_pin_code=1234
read -p "Dear user give your pin code 4 digits:" pin
let i=1
while [ $i -lt 4 ]
do
if [ $pin = $local_pin_code ]
then
echo "Success"
break
else
read -p "plz pin code from 4 digits:" pin
let i++ 
fi
done
