#!/bin/bash
read -p "enter today's day:" a
read -p "enter this month:" b
read -p "enter any day:" c
read -p "enter any month:" d
if [[ $b $d -le 12 || $b -gt $d ]]; then
echo "this date is already passed"
elif [[ $b -eq $d || $b $d -le 12 || $a -gt $c ]]; then
echo "this date is already passed"
elif [[ $b -eq $d || $c -gt $a ]]; then
echo "this date is not passed"
else
echo "this date is not passed"
fi 
