#!/bin/bash

file="current"
(find $HOME) > $file

for (( i = 1; i <= $#; i++ )); do
	array[$i]=0
done

if [ $# -ge 1 ]; then
	while read -r line
	do
		for (( i = 1; i <= $#; i++ )); do
			if [[ $(echo $line | grep -w $1) ]]; then
				let array[$i]=${array[$i]}+1
			fi
		done
	done < $file
	rm $file
	
	for (( i = 1; i <= $#; i++ ));
	do
		echo "number of files whose name is "\$$1" = ${array[$i]}"
	done
	
else
	echo "You entered wrong number of arguments"
fi
