#!/bin/bash

file="current"
(find $HOME) > $file

if [ $# -eq 1 ]; then
	while read -r line
	do
		if [[ $(echo $line | grep -w $1) ]]; then
			echo "$line"
		fi
	done < $file
	rm $file
else
	echo "You should enter just one filename"
fi
