#!/bin/bash

file="current"
(find $HOME) > $file

i=1
while [ i -le $# ]; do
	array[$i]=0
	let i=$i+1
done

if [ $# -ge 1 ]; then
	while read -r line
	do
		i=1
		while [i -le $#]; do
			if [[ $(echo $line | grep -w $1) ]]; then
				let array[$i]=${array[$i]}+1
			fi
			let i=$i+1
		done
	done < $file
	rm $file
	
	i=1
	while [i -le $#]; 
	do
		echo "number of files whose name is "\$$1" = ${array[$i]}"
		let i=$i+1
	done
	
else
	echo "You entered wrong number of arguments"
fi
