maze : main.c Stack.c ExplorationMarker.c Solution.c Cell.c
	gcc main.c Stack.c ExplorationMarker.c Solution.c Cell.c -I include -L. -lMaze -o maze -lm
	
simple : ez.c Cell.c
	gcc ez.c Cell.c -I include -L. -lMaze -lm -o simple
