#!/bin/bash
read -p "Enter salary:" a
read -p "Enter expense:" b
if [ $a -eq $b ]; then
echo "salary and expense are equal"
elif [ $a -gt $b ]; then
echo "profit is $((a-b))"
else
echo "loss is $((b-a))"
fi


